#!/bin/bash
# copied from http://www.matejunkie.com/howto-nginx-with-php-and-passenger-mod_rails-at-once/
PHP_SCRIPT=/usr/bin/php5-fcgi
RETVAL=0
case "$1" in
        start)
                echo "Starting fastcgi"
                $PHP_SCRIPT
                RETVAL=$?
  ;;
        stop)
                echo "Stopping fastcgi"
                killall -9 php-cgi
                RETVAL=$?
  ;;
        restart)
                echo "Restarting fastcgi"
                killall -9 php-cgi
                $PHP_SCRIPT
                RETVAL=$?
  ;;
        *)
                echo "Usage: php-fastcgi {start|stop|restart}"
                exit 1
  ;;
esac
exit $RETVAL
